# Generated by Django 5.0.2 on 2024-03-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('type', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EntityImages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='entity')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateField(auto_now=True)),
                ('startDate', models.DateField()),
                ('closeDate', models.DateField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
