# Generated by Django 5.0.4 on 2024-04-06 07:24

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_rename_closedate_order_close_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=django_enum.fields.EnumCharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('ROOM', 'Room'), ('OFFICE', 'Office'), ('LAND', 'Land'), ('OTHER', 'Other')], max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_enum.fields.EnumCharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], max_length=8),
        ),
    ]
