# Generated by Django 5.0.3 on 2024-03-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_creationdate_user_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profilePhoto',
            new_name='profile_photo',
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=20),
        ),
    ]
